using System.Buffers.Binary; using System.Runtime.InteropServices; using System.Text;
namespace ClipSync.Core;
public enum MessageType:byte{Text=1,Hello=2,Ack=3,Ping=4,Image=5,State=6,Pong=7}
public sealed record ClipMessage(MessageType Type,string? Text=null,byte[]? Bytes=null,long Lamport=0,string? DeviceId=null);
public static class FrameCodec{public const int HeaderSize=9,MaxPayloadLength=16 * 1024 * 1024;static readonly byte[] Magic="CSP1"u8.ToArray();public static byte[] Encode(ClipMessage m){var p=m.Type switch{MessageType.State=>SessionProtocol.EncodeState(m),MessageType.Text=>Encoding.UTF8.GetBytes(m.Text??""),MessageType.Image=>m.Bytes??[],MessageType.Hello=>Hello(m),_=>[]};if(p.Length>MaxPayloadLength)throw new InvalidDataException("OversizeLength");var o=new byte[9+p.Length];Magic.CopyTo(o,0);o[4]=(byte)m.Type;BinaryPrimitives.WriteInt32BigEndian(o.AsSpan(5),p.Length);p.CopyTo(o,9);return o;}static byte[] Hello(ClipMessage m){var d=Encoding.UTF8.GetBytes(m.DeviceId??"");var p=new byte[10+d.Length];BinaryPrimitives.WriteInt64BigEndian(p,m.Lamport);BinaryPrimitives.WriteUInt16BigEndian(p.AsSpan(8), (ushort)d.Length);d.CopyTo(p,10);return p;}public static ClipMessage Decode(byte[] f){if(f.Length<9||!f[..4].SequenceEqual(Magic))throw new InvalidDataException("BadMagic");var t=(MessageType)f[4];if(!Enum.IsDefined(t))throw new InvalidDataException("UnknownType");var n=BinaryPrimitives.ReadInt32BigEndian(f.AsSpan(5,4));if(n<0||n>MaxPayloadLength)throw new InvalidDataException("OversizeLength");if(f.Length!=9+n)throw new InvalidDataException();var q=f[9..];if(t==MessageType.Hello&&(q.Length<10||q.Length!=10+BinaryPrimitives.ReadUInt16BigEndian(q.AsSpan(8))))throw new InvalidDataException("InvalidHello");return t switch{MessageType.State=>SessionProtocol.DecodeState(q),MessageType.Text=>new(t,Text:Encoding.UTF8.GetString(q)),MessageType.Image=>new(t,Bytes:q),MessageType.Hello=>new(t,Lamport:BinaryPrimitives.ReadInt64BigEndian(q),DeviceId:Encoding.UTF8.GetString(q[10..])),_=>new(t)};}}
public sealed class FrameReader{readonly List<byte>b=[];public IEnumerable<ClipMessage> Push(byte[] x){b.AddRange(x);while(b.Count>=9){var a=b.ToArray();var n=BinaryPrimitives.ReadInt32BigEndian(a.AsSpan(5,4));if(n<0||n>FrameCodec.MaxPayloadLength)throw new InvalidDataException();if(a.Length<9+n)yield break;b.RemoveRange(0,9+n);yield return FrameCodec.Decode(a[..(9+n)]);}}}
public sealed class LamportClock{public long Value;public long Local()=>++Value;public long Observe(long r){Value=Math.Max(Value,r)+1;return Value;}}
public sealed record ClipVersion(long Lamport,string DeviceId,string Hash,ClipMessage Message):IComparable<ClipVersion>{public int CompareTo(ClipVersion? o)=>o is null?1:Lamport!=o.Lamport?Lamport.CompareTo(o.Lamport):string.CompareOrdinal(DeviceId,o.DeviceId);}
public static class HashGuard{public static bool ShouldApply(string h,string? last,ISet<string>s)=>h!=last&&s.Add(h);}
public sealed class PendingSlot{public ClipVersion? Value;public void Put(ClipVersion v){if(Value is null||v.CompareTo(Value)>0)Value=v;}public ClipVersion? Take()=>Value is null?null:Value;}
public sealed class SendScheduler{public ClipVersion? Text,Image;public void Offer(ClipVersion v){if(v.Message.Type==MessageType.Text){Text=v;Image=null;}else Image=v;}public ClipVersion? Next(){var x=Text??Image;if(x?.Message.Type==MessageType.Text)Text=null;else Image=null;return x;}}

public enum EngineState{Disconnected,Handshaking,Connected,Paused}
public sealed class InMemoryTransport{public readonly Queue<byte[]> A=new(),B=new();public void Send(bool fromA,byte[] f)=>(fromA?B:A).Enqueue(f);}
public sealed class SyncEngine{public EngineState State{get;private set;}=EngineState.Disconnected;public readonly PendingSlot Pending=new();public readonly SendScheduler Scheduler=new();public readonly HashSet<string> Seen=[];public void Connect()=>State=EngineState.Connected;public void Disconnect()=>State=EngineState.Disconnected;public void Pause()=>State=EngineState.Paused;public void Resume()=>State=EngineState.Connected;public bool Apply(ClipVersion v){if(!HashGuard.ShouldApply(v.Hash,null,Seen))return false;return true;}public void Local(ClipVersion v){if(State==EngineState.Connected)Scheduler.Offer(v);else Pending.Put(v);}}
