using System.Threading; using System.Windows; using ClipSync.Windows.UI; using ClipSync.Windows.Logging; using ClipSync.Windows.Theme; using ClipSync.Windows.Transport; using ClipSync.Windows.Security; using ClipSync.Windows.Clipboard; using ClipSync.Core;
namespace ClipSync.Windows;
public partial class App : System.Windows.Application
{
 Mutex? _mutex; TrayIconManager? _tray; StatusWindow? _window; CertificateStore? _store; SyncServer? _server; ClipboardWatcher? _clipboard; bool _paused; bool _ownsMutex;
 protected override void OnStartup(StartupEventArgs e){base.OnStartup(e);_mutex=new Mutex(true,"ClipSync-SingleInstance-48653",out var created);_ownsMutex=created;if(!created){Shutdown();return;}FileLogger.Instance.Info($"FerryClip v{typeof(App).Assembly.GetName().Version?.ToString(3)} starting (Phase 8.5)");ThemeManager.Initialize();_store=new CertificateStore();_server=new SyncServer(_store);_clipboard=new ClipboardWatcher();_window=new StatusWindow(BeginPairing,TogglePause,ForgetPhone,StartupManager.IsEnabled,StartupManager.SetEnabled);_server.ReplayOnConnect=ReconnectPreferences.Enabled;_tray=new TrayIconManager(_window,_server.ReplayOnConnect,value=>{_server.ReplayOnConnect=value;ReconnectPreferences.Enabled=value;});
 _window.PhoneEnabledRequested=(id,enabled)=>_server.EnablePhone(id,enabled); _window.PhonePausedRequested=(id,paused)=>_server.PausePhone(id,paused); _window.PhoneForgetRequested=id=>_server.ForgetPhone(id); _window.PhoneRenameRequested=(id,name)=>_server.RenamePhone(id,name);
 _window.ConnectionRequested=()=>{_server.SetConnectionsEnabled(!_server.ConnectionsEnabled);RefreshPhone();}; _window.RenameRequested=name=>{_store.PhoneName=name;RefreshPhone();}; RefreshPhone();
 _server.Notice+=message=>Dispatcher.BeginInvoke(new Action(()=>{if(!_server.PairingOpen) _window.SetPairCode(message);RefreshPhone();_tray.ShowNotice(message);}));
 _server.PairingCodeAvailable+=code=>Dispatcher.Invoke(()=>{_window.SetPairCode(code);RefreshPhone();});_server.ConnectionChanged+=connected=>Dispatcher.Invoke(()=>{_window.SetStatus(_paused?"Paused":connected?"Connected":"Waiting",connected?"Secure clipboard connection.":_server.HasPairedPhone?"Connect from your phone when ready.":"Generate a code to connect your phone.");RefreshPhone();});_server.ClipboardSink=text=>Dispatcher.Invoke(()=>{if(_paused)return true;var applied=_clipboard.WriteText(text);if(applied){var h=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(text)));FileLogger.Instance.Info($"Phone clipboard applied: text {text.Length} chars hash {h[..6]}");}return applied;});_clipboard.TextChanged+=text=>{if(!_paused){var h=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(text)));_server.Broadcast(text);FileLogger.Instance.Info($"Clipboard sent: text {text.Length} chars hash {h[..6]}");}};_server.Start();if(e.Args.Any(arg=>string.Equals(arg,"--show",StringComparison.OrdinalIgnoreCase)))Dispatcher.BeginInvoke(new Action(()=>_window.ShowPopover()));}
 void RefreshPhone(){if(_server is not null) _window?.SetPhones(_server.Phones);}
 void ForgetPhone(){try{_server?.ForgetPairedPhone();}catch(Exception ex){FileLogger.Instance.Warn("Could not forget phone: "+ex.GetType().Name);_window?.SetPairCode("Could not remove saved pairing. Existing trust was retained; check the log folder.");}}
 void BeginPairing(){_server?.BeginPairing();_window?.ShowPopover();}
 bool TogglePause(){_paused=!_paused;if(_server is not null)_server.Paused=_paused;_window?.SetStatus(_paused?"Paused":_server?.Status ?? "Waiting",_paused?"Syncing is paused on this PC.":_server?.Status == "Connected"?"Secure device connected. Clipboard sync is active.":"Syncing will resume when a device connects.");return _paused;}
 protected override void OnExit(ExitEventArgs e){if(!_ownsMutex){_mutex?.Dispose();base.OnExit(e);return;}FileLogger.Instance.Info("FerryClip shutting down");_clipboard?.Dispose();_server?.Dispose();_tray?.Dispose();_store?.Dispose();ThemeManager.Shutdown();_mutex?.ReleaseMutex();_mutex?.Dispose();FileLogger.Instance.Dispose();base.OnExit(e);}
}
