<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Version>0.8.11.0</Version>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>FerryClip</AssemblyName>
    <RootNamespace>ClipSync.Windows</RootNamespace>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClipSync.Core\ClipSync.Core.csproj" />
    <Resource Include="Assets\ferryclip_logo.png" />
  </ItemGroup>

</Project>
